In [ ]:
import pandas as pd

In [40]:
# read csv file 
df=pd.read_csv("dataset.csv")

df.head()

,order_date,customer_id,product_category,order_amount,discount_percent,discount_amount,final_price,quantity,shipping_days,delivery_date,order_status,refund_status,customer_rating,payment_method
0,2023-03-22,CUST_0087,electronics,72.230845,25.0,18.057711,54.173134,8,3.964745,2023-03-25,Completed,No,5.0,Debit Card
1,2023-11-09,CUST_0140,ELECTRONICS,247.985448,25.0,61.996362,185.989086,3,4.314526,NaN,Pending,No,5.0,Credit card
2,2024-01-20,CUST_0007,Sports,242.611682,NaN,0.000000,242.611682,7,4.717731,2024-01-24,Completed,No,5.0,Credit card
3,2023-06-08,CUST_0030,Home & Garden,1800.303058,NaN,0.000000,1800.303058,9,7.652650,2023-06-15,Completed,No,5.0,CREDIT CARD
4,2023-03-04,CUST_0014,Electronics,236.575855,NaN,0.000000,236.575855,2,5.659466,2023-03-09,Completed,No,4.0,CREDIT CARD

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203 entries, 0 to 202
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_date        203 non-null    object
 1   customer_id       203 non-null    object
 2   product_category  203 non-null    object
 3   order_amount      203 non-null    float64
 4   discount_percent  142 non-null    float64
 5   discount_amount   203 non-null    float64
 6   final_price       203 non-null    float64
 7   quantity          203 non-null    int64
 8   shipping_days     191 non-null    float64
 9   delivery_date     152 non-null    object
 10  order_status      203 non-null    object
 11  refund_status     191 non-null    object
 12  customer_rating   176 non-null    float64
 13  payment_method    203 non-null    object
dtypes: float64(6), int64(1), object(7)
memory usage: 22.3+ KB

In [42]:
df.describe()

,order_amount,discount_percent,discount_amount,final_price,quantity,shipping_days,customer_rating
count,203.000000,142.000000,203.000000,203.000000,203.000000,191.000000,176.000000
mean,1211.880094,11.725352,95.971013,1115.909081,7.975369,7.338221,3.664773
std,5043.227290,8.650949,605.916492,4668.315504,18.584950,3.571606,1.408589
min,13.964870,0.000000,0.000000,13.266626,-3.000000,1.474159,1.000000
25%,93.267331,5.000000,0.000000,84.876275,3.000000,4.888861,2.000000
50%,198.930584,10.000000,5.380036,176.628497,5.000000,6.536953,4.000000
75%,283.780764,20.000000,33.386144,262.383237,7.500000,9.136835,5.000000
max,44449.766867,25.000000,8300.837591,44449.766867,170.000000,21.385633,5.000000

In [ ]:
df.shape

SyntaxError: invalid syntax (4215238244.py, line 3)

In [ ]:
df.columns

Index(['order_date', 'customer_id', 'product_category', 'order_amount',
       'discount_percent', 'discount_amount', 'final_price', 'quantity',
       'shipping_days', 'delivery_date', 'order_status', 'refund_status',
       'customer_rating', 'payment_method'],
      dtype='object')

In [ ]:
df.dtypes

order_date           object
customer_id          object
product_category     object
order_amount        float64
discount_percent    float64
discount_amount     float64
final_price         float64
quantity              int64
shipping_days       float64
delivery_date        object
order_status         object
refund_status        object
customer_rating     float64
payment_method       object
dtype: object

## selecting data

In [ ]:
df[['customer_id','order_amount','payment_method']]

    customer_id  order_amount payment_method
0     CUST_0087     72.230845     Debit Card
1     CUST_0140    247.985448    Credit card
2     CUST_0007    242.611682    Credit card
3     CUST_0030   1800.303058    CREDIT CARD
4     CUST_0014    236.575855    CREDIT CARD
..          ...           ...            ...
198   CUST_0008    248.609202     Debit Card
199   CUST_0007     89.448727        Unknown
200   CUST_0096   1387.833108    Credit card
201   CUST_0025    179.693364        Unknown
202   CUST_0009   1107.803130         PayPal

[203 rows x 3 columns]

In [ ]:
df.iloc[0:5]

,order_date,customer_id,product_category,order_amount,discount_percent,discount_amount,final_price,quantity,shipping_days,delivery_date,order_status,refund_status,customer_rating,payment_method
0,2023-03-22,CUST_0087,electronics,72.230845,25.0,18.057711,54.173134,8,3.964745,2023-03-25,Completed,No,5.0,Debit Card
1,2023-11-09,CUST_0140,ELECTRONICS,247.985448,25.0,61.996362,185.989086,3,4.314526,NaN,Pending,No,5.0,Credit card
2,2024-01-20,CUST_0007,Sports,242.611682,NaN,0.000000,242.611682,7,4.717731,2024-01-24,Completed,No,5.0,Credit card
3,2023-06-08,CUST_0030,Home & Garden,1800.303058,NaN,0.000000,1800.303058,9,7.652650,2023-06-15,Completed,No,5.0,CREDIT CARD
4,2023-03-04,CUST_0014,Electronics,236.575855,NaN,0.000000,236.575855,2,5.659466,2023-03-09,Completed,No,4.0,CREDIT CARD

In [ ]:
df.loc[df['customer_id'] == "CUST_0009"]

,order_date,customer_id,product_category,order_amount,discount_percent,discount_amount,final_price,quantity,shipping_days,delivery_date,order_status,refund_status,customer_rating,payment_method
9,2023-05-31,CUST_0009,Clothing,220.575045,15.0,33.086257,187.488788,8,16.027394,2023-06-16,Completed,Refunded,NaN,Apple Pay
16,2023-07-10,CUST_0009,Books,189.293626,25.0,47.323407,141.970220,170,1.969204,NaN,Pending,No,4.0,Unknown
59,2023-03-18,CUST_0009,clothing,210.597175,25.0,52.649294,157.947881,8,5.598051,NaN,Pending,No,4.0,Credit Card
84,2023-03-24,CUST_0009,Apparel,171.241461,0.0,0.000000,171.241461,5,5.704061,2023-03-29,Completed,No,1.0,Debit Card
102,2023-01-29,CUST_0009,ELECTRONICS,168.911846,NaN,0.000000,168.911846,8,10.208934,2023-02-08,Completed,No,5.0,CREDIT CARD
158,2023-10-12,CUST_0009,Clothing,31.854128,NaN,0.000000,31.854128,5,11.222148,2023-10-09,Completed,Refunded,NaN,Debit Card
185,2023-05-03,CUST_0009,Home & Garden,184.806746,20.0,36.961349,147.845397,8,8.165411,2023-05-11,Completed,No,4.0,Apple Pay
187,2023-04-16,CUST_0009,clothing,48.623686,25.0,12.155922,36.467765,5,5.600703,2023-04-21,Completed,No,5.0,Credit card
202,2023-05-19,CUST_0009,Clothing,1107.803130,25.0,276.950783,830.852348,3,9.856111,2023-05-28,Cancelled,No,2.0,PayPal

In [ ]:
df['customer_id'].value_counts()

customer_id
CUST_0009    9
CUST_0018    9
CUST_0019    8
CUST_0007    8
CUST_0008    8
            ..
CUST_0137    1
CUST_0088    1
CUST_0078    1
CUST_0081    1
CUST_0096    1
Name: count, Length: 63, dtype: int64

In [ ]:
new_data=df.drop('refund_status',axis=1)
new_data

,order_date,customer_id,product_category,order_amount,discount_percent,discount_amount,final_price,quantity,shipping_days,delivery_date,order_status,customer_rating,payment_method
0,2023-03-22,CUST_0087,electronics,72.230845,25.0,18.057711,54.173134,8,3.964745,2023-03-25,Completed,5.0,Debit Card
1,2023-11-09,CUST_0140,ELECTRONICS,247.985448,25.0,61.996362,185.989086,3,4.314526,NaN,Pending,5.0,Credit card
2,2024-01-20,CUST_0007,Sports,242.611682,NaN,0.000000,242.611682,7,4.717731,2024-01-24,Completed,5.0,Credit card
3,2023-06-08,CUST_0030,Home & Garden,1800.303058,NaN,0.000000,1800.303058,9,7.652650,2023-06-15,Completed,5.0,CREDIT CARD
4,2023-03-04,CUST_0014,Electronics,236.575855,NaN,0.000000,236.575855,2,5.659466,2023-03-09,Completed,4.0,CREDIT CARD
...,...,...,...,...,...,...,...,...,...,...,...,...,...
198,2023-06-30,CUST_0008,Home & Garden,248.609202,25.0,62.152301,186.456902,2,6.927016,2023-07-06,Cancelled,5.0,Debit Card
199,2023-03-22,CUST_0007,electronics,89.448727,10.0,8.944873,80.503854,2,10.938882,NaN,Pending,1.0,Unknown
200,2023-12-02,CUST_0096,Home & Garden,1387.833108,20.0,277.566622,1110.266487,1,NaN,NaN,Pending,4.0,Credit card
201,2023-03-02,CUST_0025,Home & Garden,179.693364,20.0,35.938673,143.754691,3,10.202383,2023-02-23,Completed,2.0,Unknown
202,2023-05-19,CUST_0009,Clothing,1107.803130,25.0,276.950783,830.852348,3,9.856111,2023-05-28,Cancelled,2.0,PayPal

In [ ]:
new_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203 entries, 0 to 202
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_date        203 non-null    object
 1   customer_id       203 non-null    object
 2   product_category  203 non-null    object
 3   order_amount      203 non-null    float64
 4   discount_percent  142 non-null    float64
 5   discount_amount   203 non-null    float64
 6   final_price       203 non-null    float64
 7   quantity          203 non-null    int64
 8   shipping_days     191 non-null    float64
 9   delivery_date     152 non-null    object
 10  order_status      203 non-null    object
 11  customer_rating   176 non-null    float64
 12  payment_method    203 non-null    object
dtypes: float64(6), int64(1), object(6)
memory usage: 20.7+ KB

In [48]:

df_clean=df.dropna()
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 92 entries, 0 to 202
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_date        92 non-null     object
 1   customer_id       92 non-null     object
 2   product_category  92 non-null     object
 3   order_amount      92 non-null     float64
 4   discount_percent  92 non-null     float64
 5   discount_amount   92 non-null     float64
 6   final_price       92 non-null     float64
 7   quantity          92 non-null     int64
 8   shipping_days     92 non-null     float64
 9   delivery_date     92 non-null     object
 10  order_status      92 non-null     object
 11  refund_status     92 non-null     object
 12  customer_rating   92 non-null     float64
 13  payment_method    92 non-null     object
dtypes: float64(6), int64(1), object(7)
memory usage: 10.8+ KB